theme = "slick"
icons = "awesome"


[[block]]
block = "backlight"


[[block]]
block = "bluetooth"
mac = "30:C0:1B:6E:E4:D9"


[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 60


[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB"
format_swap = "{SUg}GB/{STg}GB"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95


[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true
ip = true
interval = 5
speed_up = false
speed_down = false


[[block]]
block = "sound"
step_width = 3


[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Asia/Kolkata"
interval = 60
